# Generated by Django 5.2.6 on 2025-09-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_picture',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
    ]
