# Generated by Django 5.2.6 on 2025-09-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_vehicle_vehicle_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
